### ISSUE TITLE
Add methods to abstract exception

### ISSUE THREAD

**Issue by anton-moskalenko** [anton-moskalenko/rf-exception#3]
## ToDo

- [x] Add public function __toString()
- [x] Add public function getArray()
- [x] Add params methods (setParam, getParam)

- [x] Fix review https://github.com/anton-moskalenko/rf-exception/commit/44427c2fba8a47f5f81c14c6d29bacf082c9a1a9

**Comment by anton-moskalenko** [comment]
## Commits

[gh:3] Add methods to abstract exception.

**Comment by anton-moskalenko** [comment]
Done.
