### ISSUE TITLE
Integrate this library at Rune Framework

### ISSUE THREAD

**Issue by anton-moskalenko** [anton-moskalenko/rf-exception#4]
## ToDo

- [ ] Bind through composer
- [ ] Change existing exceptions
- [ ] Delete basic exceptions at RF project

**Comment by anton-moskalenko** [comment]
## Commits

**Comment by anton-moskalenko** [comment]
## Reviews
